#!/bin/bash

echo "Input max percent WITHOUT \"%\":"

# Необходимо ввести максимально возможный процент заполненности папки /LOG
read MAXPCENT

PCENT=$((`df -k /LOG | tail -1 | awk '{print $5}' | cut -d '%' -f 1`))

# Проверка заполненности папки /LOG
if [ $PCENT -gt $MAXPCENT ]

then

# Заходим в папку /LOG
cd /LOG/

# Создаём список файлов, отсортированный по дате, три самых старых файла
list=$(ls -t | head -n 3)

# Создание архива последних файлов папки /LOG
tar -zvf LOG.tar.gz $list

# Перемещение архива в папку /BACKUP
mv /LOG.tar.gz /BACKUP

# Удаление этих файлов из папки /LOG
rm $list

echo "Directory /LOG was overfilled. Three old files were archivated and moved to /BACKUP. Now /LOG is empty."

else

echo "Use percent is $PCENT%, so it's OK."
